export enum SkillCategory {
  // ─────────────────────────────────────────────────────────────
  // SOFTWARE DEVELOPMENT & TECHNOLOGY
  // ─────────────────────────────────────────────────────────────

  // Frontend Development
  FRONTEND_DEVELOPMENT = 'FRONTEND_DEVELOPMENT',
  REACT_NEXTJS_DEVELOPMENT = 'REACT_NEXTJS_DEVELOPMENT',
  VUE_NUXT_DEVELOPMENT = 'VUE_NUXT_DEVELOPMENT',
  ANGULAR_DEVELOPMENT = 'ANGULAR_DEVELOPMENT',
  WEB_PERFORMANCE_OPTIMIZATION = 'WEB_PERFORMANCE_OPTIMIZATION',
  ACCESSIBILITY_A11Y_DEVELOPMENT = 'ACCESSIBILITY_A11Y_DEVELOPMENT',
  WEB3_FRONTEND_DAPP_DEVELOPMENT = 'WEB3_FRONTEND_DAPP_DEVELOPMENT',

  // Backend Development
  BACKEND_DEVELOPMENT = 'BACKEND_DEVELOPMENT',
  API_DESIGN_REST_GRAPHQL = 'API_DESIGN_REST_GRAPHQL',
  MICROSERVICES_ARCHITECTURE = 'MICROSERVICES_ARCHITECTURE',
  SERVERLESS_EDGE_COMPUTING = 'SERVERLESS_EDGE_COMPUTING',
  NODE_TYPESCRIPT_DEVELOPMENT = 'NODE_TYPESCRIPT_DEVELOPMENT',
  PYTHON_BACKEND_DEVELOPMENT = 'PYTHON_BACKEND_DEVELOPMENT',
  GO_RUST_SYSTEMS_DEVELOPMENT = 'GO_RUST_SYSTEMS_DEVELOPMENT',
  JAVA_JVM_DEVELOPMENT = 'JAVA_JVM_DEVELOPMENT',
  DOTNET_CSHARP_DEVELOPMENT = 'DOTNET_CSHARP_DEVELOPMENT',

  // Mobile
  MOBILE_APP_DEVELOPMENT = 'MOBILE_APP_DEVELOPMENT',
  IOS_SWIFT_DEVELOPMENT = 'IOS_SWIFT_DEVELOPMENT',
  ANDROID_KOTLIN_DEVELOPMENT = 'ANDROID_KOTLIN_DEVELOPMENT',
  REACT_NATIVE_DEVELOPMENT = 'REACT_NATIVE_DEVELOPMENT',
  FLUTTER_DART_DEVELOPMENT = 'FLUTTER_DART_DEVELOPMENT',

  // DevOps & Cloud
  DEVOPS_CLOUD_INFRASTRUCTURE = 'DEVOPS_CLOUD_INFRASTRUCTURE',
  CI_CD_PIPELINE_ENGINEERING = 'CI_CD_PIPELINE_ENGINEERING',
  INFRASTRUCTURE_AS_CODE = 'INFRASTRUCTURE_AS_CODE',
  KUBERNETES_CONTAINER_ORCHESTRATION = 'KUBERNETES_CONTAINER_ORCHESTRATION',
  AWS_CLOUD_ENGINEERING = 'AWS_CLOUD_ENGINEERING',
  GCP_CLOUD_ENGINEERING = 'GCP_CLOUD_ENGINEERING',
  AZURE_CLOUD_ENGINEERING = 'AZURE_CLOUD_ENGINEERING',
  SITE_RELIABILITY_ENGINEERING = 'SITE_RELIABILITY_ENGINEERING',
  PLATFORM_ENGINEERING = 'PLATFORM_ENGINEERING',
  FINOPS_CLOUD_COST_OPTIMIZATION = 'FINOPS_CLOUD_COST_OPTIMIZATION',

  // Database
  DATABASE_MANAGEMENT = 'DATABASE_MANAGEMENT',
  SQL_RELATIONAL_DATABASES = 'SQL_RELATIONAL_DATABASES',
  NOSQL_DOCUMENT_DATABASES = 'NOSQL_DOCUMENT_DATABASES',
  VECTOR_DATABASES_SEARCH = 'VECTOR_DATABASES_SEARCH',
  DATA_WAREHOUSING_LAKE_ARCHITECTURE = 'DATA_WAREHOUSING_LAKE_ARCHITECTURE',
  REAL_TIME_STREAMING_DATABASES = 'REAL_TIME_STREAMING_DATABASES',

  // Cybersecurity
  CYBERSECURITY_INFORMATION_SECURITY = 'CYBERSECURITY_INFORMATION_SECURITY',
  APPLICATION_SECURITY_APPSEC = 'APPLICATION_SECURITY_APPSEC',
  PENETRATION_TESTING_RED_TEAMING = 'PENETRATION_TESTING_RED_TEAMING',
  SECURITY_OPERATIONS_SOC = 'SECURITY_OPERATIONS_SOC',
  CLOUD_SECURITY_ARCHITECTURE = 'CLOUD_SECURITY_ARCHITECTURE',
  DEVSECOPS = 'DEVSECOPS',
  THREAT_INTELLIGENCE_ANALYSIS = 'THREAT_INTELLIGENCE_ANALYSIS',
  IDENTITY_ACCESS_MANAGEMENT = 'IDENTITY_ACCESS_MANAGEMENT',
  DIGITAL_FORENSICS_INCIDENT_RESPONSE = 'DIGITAL_FORENSICS_INCIDENT_RESPONSE',

  // Data Science & Analytics
  DATA_SCIENCE_ANALYTICS = 'DATA_SCIENCE_ANALYTICS',
  DATA_ENGINEERING_PIPELINES = 'DATA_ENGINEERING_PIPELINES',
  BUSINESS_INTELLIGENCE_REPORTING = 'BUSINESS_INTELLIGENCE_REPORTING',
  STATISTICAL_MODELING_ANALYSIS = 'STATISTICAL_MODELING_ANALYSIS',
  DATA_VISUALIZATION = 'DATA_VISUALIZATION',

  // AI & Machine Learning
  ARTIFICIAL_INTELLIGENCE_MACHINE_LEARNING = 'ARTIFICIAL_INTELLIGENCE_MACHINE_LEARNING',
  DEEP_LEARNING_NEURAL_NETWORKS = 'DEEP_LEARNING_NEURAL_NETWORKS',
  NATURAL_LANGUAGE_PROCESSING = 'NATURAL_LANGUAGE_PROCESSING',
  COMPUTER_VISION = 'COMPUTER_VISION',
  REINFORCEMENT_LEARNING = 'REINFORCEMENT_LEARNING',
  MLOPS_AI_INFRASTRUCTURE = 'MLOPS_AI_INFRASTRUCTURE',
  AI_SAFETY_ALIGNMENT_RESEARCH = 'AI_SAFETY_ALIGNMENT_RESEARCH',
  GENERATIVE_AI_LLM_ENGINEERING = 'GENERATIVE_AI_LLM_ENGINEERING',
  PROMPT_ENGINEERING = 'PROMPT_ENGINEERING',

  // Game Development
  GAME_DEVELOPMENT = 'GAME_DEVELOPMENT',
  UNITY_DEVELOPMENT = 'UNITY_DEVELOPMENT',
  UNREAL_ENGINE_DEVELOPMENT = 'UNREAL_ENGINE_DEVELOPMENT',
  GAME_DESIGN_SYSTEMS = 'GAME_DESIGN_SYSTEMS',
  XR_AR_VR_DEVELOPMENT = 'XR_AR_VR_DEVELOPMENT',
  REAL_TIME_GRAPHICS_SHADERS = 'REAL_TIME_GRAPHICS_SHADERS',

  // Embedded & IoT
  EMBEDDED_SYSTEMS_IOT = 'EMBEDDED_SYSTEMS_IOT',
  FIRMWARE_DEVELOPMENT = 'FIRMWARE_DEVELOPMENT',
  RTOS_BARE_METAL_PROGRAMMING = 'RTOS_BARE_METAL_PROGRAMMING',
  IOT_PLATFORM_CONNECTIVITY = 'IOT_PLATFORM_CONNECTIVITY',
  ROBOTICS_CONTROL_SYSTEMS = 'ROBOTICS_CONTROL_SYSTEMS',

  // QA & Testing
  QA_SOFTWARE_TESTING = 'QA_SOFTWARE_TESTING',
  TEST_AUTOMATION_ENGINEERING = 'TEST_AUTOMATION_ENGINEERING',
  PERFORMANCE_LOAD_TESTING = 'PERFORMANCE_LOAD_TESTING',
  MANUAL_EXPLORATORY_TESTING = 'MANUAL_EXPLORATORY_TESTING',
  CHAOS_ENGINEERING_RESILIENCE = 'CHAOS_ENGINEERING_RESILIENCE',

  // Blockchain & Web3
  BLOCKCHAIN_WEB3 = 'BLOCKCHAIN_WEB3',
  SMART_CONTRACT_DEVELOPMENT = 'SMART_CONTRACT_DEVELOPMENT',
  DEFI_PROTOCOL_ENGINEERING = 'DEFI_PROTOCOL_ENGINEERING',
  NFT_TOKENIZATION_PLATFORMS = 'NFT_TOKENIZATION_PLATFORMS',
  CRYPTO_PROTOCOL_DESIGN = 'CRYPTO_PROTOCOL_DESIGN',
  ZERO_KNOWLEDGE_PROOF_ENGINEERING = 'ZERO_KNOWLEDGE_PROOF_ENGINEERING',

  // Developer Experience
  DEVELOPER_EXPERIENCE_DEVTOOLS = 'DEVELOPER_EXPERIENCE_DEVTOOLS',
  OPEN_SOURCE_LIBRARY_DEVELOPMENT = 'OPEN_SOURCE_LIBRARY_DEVELOPMENT',
  TECHNICAL_DOCUMENTATION_WRITING = 'TECHNICAL_DOCUMENTATION_WRITING',
  SDK_CLI_TOOLING = 'SDK_CLI_TOOLING',

  // ─────────────────────────────────────────────────────────────
  // DESIGN & CREATIVE MEDIA
  // ─────────────────────────────────────────────────────────────

  // UI/UX & Product Design
  UI_UX_PRODUCT_DESIGN = 'UI_UX_PRODUCT_DESIGN',
  DESIGN_SYSTEMS_COMPONENT_LIBRARIES = 'DESIGN_SYSTEMS_COMPONENT_LIBRARIES',
  USER_RESEARCH_USABILITY_TESTING = 'USER_RESEARCH_USABILITY_TESTING',
  INTERACTION_DESIGN_PROTOTYPING = 'INTERACTION_DESIGN_PROTOTYPING',
  INFORMATION_ARCHITECTURE = 'INFORMATION_ARCHITECTURE',
  SERVICE_DESIGN = 'SERVICE_DESIGN',

  // Graphic Design & Branding
  GRAPHIC_DESIGN_BRANDING = 'GRAPHIC_DESIGN_BRANDING',
  VISUAL_IDENTITY_BRAND_STRATEGY = 'VISUAL_IDENTITY_BRAND_STRATEGY',
  TYPOGRAPHY_LETTERING = 'TYPOGRAPHY_LETTERING',
  ILLUSTRATION_DIGITAL_ART = 'ILLUSTRATION_DIGITAL_ART',
  PACKAGING_PRINT_DESIGN = 'PACKAGING_PRINT_DESIGN',
  EDITORIAL_PUBLICATION_DESIGN = 'EDITORIAL_PUBLICATION_DESIGN',

  // Motion & Animation
  MOTION_GRAPHICS_ANIMATION = 'MOTION_GRAPHICS_ANIMATION',
  CHARACTER_ANIMATION = 'CHARACTER_ANIMATION',
  VFX_COMPOSITING = 'VFX_COMPOSITING',
  INTERACTIVE_CREATIVE_CODING = 'INTERACTIVE_CREATIVE_CODING',

  // Video Production
  VIDEO_PRODUCTION_EDITING = 'VIDEO_PRODUCTION_EDITING',
  DOCUMENTARY_NARRATIVE_FILMMAKING = 'DOCUMENTARY_NARRATIVE_FILMMAKING',
  LIVE_STREAMING_BROADCAST = 'LIVE_STREAMING_BROADCAST',
  COLOR_GRADING_FINISHING = 'COLOR_GRADING_FINISHING',
  SCRIPTWRITING_STORYBOARDING = 'SCRIPTWRITING_STORYBOARDING',

  // Audio Production
  AUDIO_PRODUCTION_SOUND_DESIGN = 'AUDIO_PRODUCTION_SOUND_DESIGN',
  MUSIC_PRODUCTION_COMPOSITION = 'MUSIC_PRODUCTION_COMPOSITION',
  PODCAST_PRODUCTION = 'PODCAST_PRODUCTION',
  VOICEOVER_NARRATION = 'VOICEOVER_NARRATION',
  SPATIAL_AUDIO_IMMERSIVE_SOUND = 'SPATIAL_AUDIO_IMMERSIVE_SOUND',

  // 3D & Rendering
  THREE_D_MODELING_RENDERING = 'THREE_D_MODELING_RENDERING',
  PRODUCT_VISUALIZATION = 'PRODUCT_VISUALIZATION',
  ARCHITECTURAL_VISUALIZATION = 'ARCHITECTURAL_VISUALIZATION',
  GENERATIVE_AI_ART_DIRECTION = 'GENERATIVE_AI_ART_DIRECTION',
  SCULPTING_DIGITAL_FABRICATION = 'SCULPTING_DIGITAL_FABRICATION',

  // Photography
  PHOTOGRAPHY_IMAGING = 'PHOTOGRAPHY_IMAGING',
  PHOTO_RETOUCHING_POST_PROCESSING = 'PHOTO_RETOUCHING_POST_PROCESSING',
  COMMERCIAL_STUDIO_PHOTOGRAPHY = 'COMMERCIAL_STUDIO_PHOTOGRAPHY',
  DRONE_AERIAL_PHOTOGRAPHY = 'DRONE_AERIAL_PHOTOGRAPHY',

  // Architecture & Interior Design
  INTERIOR_ARCHITECTURAL_DESIGN = 'INTERIOR_ARCHITECTURAL_DESIGN',
  URBAN_LANDSCAPE_DESIGN = 'URBAN_LANDSCAPE_DESIGN',
  SPACE_PLANNING_FF_AND_E = 'SPACE_PLANNING_FF_AND_E',
  SUSTAINABLE_GREEN_DESIGN = 'SUSTAINABLE_GREEN_DESIGN',

  // Fashion & Textile
  FASHION_APPAREL_DESIGN = 'FASHION_APPAREL_DESIGN',
  TEXTILE_MATERIAL_DESIGN = 'TEXTILE_MATERIAL_DESIGN',
  COSTUME_PROP_DESIGN = 'COSTUME_PROP_DESIGN',

  // ─────────────────────────────────────────────────────────────
  // PRODUCT, PROJECT, & OPERATIONS MANAGEMENT
  // ─────────────────────────────────────────────────────────────

  PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT',
  TECHNICAL_PRODUCT_MANAGEMENT = 'TECHNICAL_PRODUCT_MANAGEMENT',
  PLATFORM_ECOSYSTEM_STRATEGY = 'PLATFORM_ECOSYSTEM_STRATEGY',
  PRODUCT_ANALYTICS_EXPERIMENTATION = 'PRODUCT_ANALYTICS_EXPERIMENTATION',

  PROJECT_MANAGEMENT_AGILE = 'PROJECT_MANAGEMENT_AGILE',
  SCRUM_MASTER_AGILE_COACHING = 'SCRUM_MASTER_AGILE_COACHING',
  PROGRAM_MANAGEMENT = 'PROGRAM_MANAGEMENT',
  TECHNICAL_PROJECT_MANAGEMENT = 'TECHNICAL_PROJECT_MANAGEMENT',
  PMO_PORTFOLIO_MANAGEMENT = 'PMO_PORTFOLIO_MANAGEMENT',

  BUSINESS_OPERATIONS_STRATEGY = 'BUSINESS_OPERATIONS_STRATEGY',
  ORGANIZATIONAL_DESIGN = 'ORGANIZATIONAL_DESIGN',
  PROCESS_IMPROVEMENT_LEAN = 'PROCESS_IMPROVEMENT_LEAN',
  VENDOR_PROCUREMENT_MANAGEMENT = 'VENDOR_PROCUREMENT_MANAGEMENT',
  WORKPLACE_FACILITIES_MANAGEMENT = 'WORKPLACE_FACILITIES_MANAGEMENT',

  SUPPLY_CHAIN_LOGISTICS = 'SUPPLY_CHAIN_LOGISTICS',
  INVENTORY_WAREHOUSE_MANAGEMENT = 'INVENTORY_WAREHOUSE_MANAGEMENT',
  IMPORT_EXPORT_TRADE_COMPLIANCE = 'IMPORT_EXPORT_TRADE_COMPLIANCE',
  LAST_MILE_DELIVERY_OPERATIONS = 'LAST_MILE_DELIVERY_OPERATIONS',

  CUSTOMER_SUCCESS_SUPPORT = 'CUSTOMER_SUCCESS_SUPPORT',
  ENTERPRISE_CUSTOMER_SUCCESS = 'ENTERPRISE_CUSTOMER_SUCCESS',
  TECHNICAL_SUPPORT_ENGINEERING = 'TECHNICAL_SUPPORT_ENGINEERING',
  COMMUNITY_DEVELOPER_RELATIONS = 'COMMUNITY_DEVELOPER_RELATIONS',
  CUSTOMER_EXPERIENCE_CX = 'CUSTOMER_EXPERIENCE_CX',

  HUMAN_RESOURCES_TALENT_ACQUISITION = 'HUMAN_RESOURCES_TALENT_ACQUISITION',
  TECHNICAL_RECRUITING = 'TECHNICAL_RECRUITING',
  COMPENSATION_BENEFITS_DESIGN = 'COMPENSATION_BENEFITS_DESIGN',
  LEARNING_DEVELOPMENT = 'LEARNING_DEVELOPMENT',
  PEOPLE_OPERATIONS_HRBP = 'PEOPLE_OPERATIONS_HRBP',
  DIVERSITY_EQUITY_INCLUSION = 'DIVERSITY_EQUITY_INCLUSION',

  LEGAL_COMPLIANCE_GOVERNANCE = 'LEGAL_COMPLIANCE_GOVERNANCE',
  CORPORATE_COMMERCIAL_LAW = 'CORPORATE_COMMERCIAL_LAW',
  INTELLECTUAL_PROPERTY_LAW = 'INTELLECTUAL_PROPERTY_LAW',
  DATA_PRIVACY_REGULATORY_COMPLIANCE = 'DATA_PRIVACY_REGULATORY_COMPLIANCE',
  EMPLOYMENT_LABOUR_LAW = 'EMPLOYMENT_LABOUR_LAW',
  CONTRACT_MANAGEMENT = 'CONTRACT_MANAGEMENT',

  // ─────────────────────────────────────────────────────────────
  // MARKETING & GROWTH
  // ─────────────────────────────────────────────────────────────

  DIGITAL_MARKETING_SEO = 'DIGITAL_MARKETING_SEO',
  SEARCH_ENGINE_OPTIMIZATION = 'SEARCH_ENGINE_OPTIMIZATION',
  PAID_SEARCH_SEM = 'PAID_SEARCH_SEM',
  PROGRAMMATIC_DISPLAY_ADVERTISING = 'PROGRAMMATIC_DISPLAY_ADVERTISING',
  EMAIL_LIFECYCLE_MARKETING = 'EMAIL_LIFECYCLE_MARKETING',
  AFFILIATE_INFLUENCER_MARKETING = 'AFFILIATE_INFLUENCER_MARKETING',

  CONTENT_STRATEGY_COPYWRITING = 'CONTENT_STRATEGY_COPYWRITING',
  LONG_FORM_CONTENT_BLOG_WRITING = 'LONG_FORM_CONTENT_BLOG_WRITING',
  UX_CONVERSION_COPYWRITING = 'UX_CONVERSION_COPYWRITING',
  VIDEO_PODCAST_CONTENT_CREATION = 'VIDEO_PODCAST_CONTENT_CREATION',
  AI_ASSISTED_CONTENT_OPERATIONS = 'AI_ASSISTED_CONTENT_OPERATIONS',

  SOCIAL_MEDIA_MANAGEMENT = 'SOCIAL_MEDIA_MANAGEMENT',
  COMMUNITY_BUILDING_MANAGEMENT = 'COMMUNITY_BUILDING_MANAGEMENT',
  CREATOR_INFLUENCER_PARTNERSHIPS = 'CREATOR_INFLUENCER_PARTNERSHIPS',
  SOCIAL_COMMERCE = 'SOCIAL_COMMERCE',

  GROWTH_HACKING_CONVERSION_OPTIMIZATION = 'GROWTH_HACKING_CONVERSION_OPTIMIZATION',
  A_B_TESTING_EXPERIMENTATION = 'A_B_TESTING_EXPERIMENTATION',
  MARKETING_ANALYTICS_ATTRIBUTION = 'MARKETING_ANALYTICS_ATTRIBUTION',
  PRODUCT_LED_GROWTH = 'PRODUCT_LED_GROWTH',

  PUBLIC_RELATIONS_BRAND_COMMUNICATIONS = 'PUBLIC_RELATIONS_BRAND_COMMUNICATIONS',
  CRISIS_COMMUNICATIONS = 'CRISIS_COMMUNICATIONS',
  EXECUTIVE_THOUGHT_LEADERSHIP = 'EXECUTIVE_THOUGHT_LEADERSHIP',
  MEDIA_PRESS_RELATIONS = 'MEDIA_PRESS_RELATIONS',
  EVENT_CONFERENCE_MARKETING = 'EVENT_CONFERENCE_MARKETING',

  BRAND_STRATEGY_POSITIONING = 'BRAND_STRATEGY_POSITIONING',
  MARKET_RESEARCH_COMPETITIVE_INTELLIGENCE = 'MARKET_RESEARCH_COMPETITIVE_INTELLIGENCE',
  PRODUCT_MARKETING = 'PRODUCT_MARKETING',
  DEVELOPER_MARKETING = 'DEVELOPER_MARKETING',

  // ─────────────────────────────────────────────────────────────
  // SALES & BUSINESS DEVELOPMENT
  // ─────────────────────────────────────────────────────────────

  ENTERPRISE_SALES_ACCOUNT_MANAGEMENT = 'ENTERPRISE_SALES_ACCOUNT_MANAGEMENT',
  SMB_SALES = 'SMB_SALES',
  TECHNICAL_SOLUTIONS_SALES_ENGINEERING = 'TECHNICAL_SOLUTIONS_SALES_ENGINEERING',
  SAAS_SALES = 'SAAS_SALES',
  CHANNEL_PARTNER_SALES = 'CHANNEL_PARTNER_SALES',

  BUSINESS_DEVELOPMENT_PARTNERSHIPS = 'BUSINESS_DEVELOPMENT_PARTNERSHIPS',
  STRATEGIC_ALLIANCES = 'STRATEGIC_ALLIANCES',
  ECOSYSTEM_PARTNER_MANAGEMENT = 'ECOSYSTEM_PARTNER_MANAGEMENT',
  MARKET_EXPANSION_STRATEGY = 'MARKET_EXPANSION_STRATEGY',

  CUSTOMER_ACQUISITION_REVENUE_OPERATIONS = 'CUSTOMER_ACQUISITION_REVENUE_OPERATIONS',
  SALES_ENABLEMENT = 'SALES_ENABLEMENT',
  CRM_ADMINISTRATION_STRATEGY = 'CRM_ADMINISTRATION_STRATEGY',
  DEMAND_GENERATION = 'DEMAND_GENERATION',
  PRICING_STRATEGY_MONETIZATION = 'PRICING_STRATEGY_MONETIZATION',

  // ─────────────────────────────────────────────────────────────
  // FINANCE, ECONOMICS, & ANALYSIS
  // ─────────────────────────────────────────────────────────────

  FINANCIAL_ANALYSIS_ACCOUNTING = 'FINANCIAL_ANALYSIS_ACCOUNTING',
  FINANCIAL_PLANNING_ANALYSIS_FPA = 'FINANCIAL_PLANNING_ANALYSIS_FPA',
  CORPORATE_ACCOUNTING = 'CORPORATE_ACCOUNTING',
  TAX_STRATEGY_COMPLIANCE = 'TAX_STRATEGY_COMPLIANCE',
  TREASURY_CASH_MANAGEMENT = 'TREASURY_CASH_MANAGEMENT',

  INVESTMENT_BANKING_ASSET_MANAGEMENT = 'INVESTMENT_BANKING_ASSET_MANAGEMENT',
  VENTURE_CAPITAL_PRIVATE_EQUITY = 'VENTURE_CAPITAL_PRIVATE_EQUITY',
  EQUITY_CREDIT_RESEARCH = 'EQUITY_CREDIT_RESEARCH',
  WEALTH_MANAGEMENT_FINANCIAL_ADVISORY = 'WEALTH_MANAGEMENT_FINANCIAL_ADVISORY',
  MERGERS_ACQUISITIONS = 'MERGERS_ACQUISITIONS',

  QUANTITATIVE_ANALYSIS_FINTECH = 'QUANTITATIVE_ANALYSIS_FINTECH',
  ALGORITHMIC_TRADING_STRATEGY = 'ALGORITHMIC_TRADING_STRATEGY',
  CRYPTO_DIGITAL_ASSET_FINANCE = 'CRYPTO_DIGITAL_ASSET_FINANCE',
  FINANCIAL_MODELING = 'FINANCIAL_MODELING',
  ACTUARIAL_SCIENCE = 'ACTUARIAL_SCIENCE',

  RISK_MANAGEMENT_AUDITING = 'RISK_MANAGEMENT_AUDITING',
  ENTERPRISE_RISK_MANAGEMENT = 'ENTERPRISE_RISK_MANAGEMENT',
  INTERNAL_AUDIT_CONTROLS = 'INTERNAL_AUDIT_CONTROLS',
  CREDIT_COUNTERPARTY_RISK = 'CREDIT_COUNTERPARTY_RISK',
  ESG_REPORTING_COMPLIANCE = 'ESG_REPORTING_COMPLIANCE',

  ECONOMIC_POLICY_RESEARCH = 'ECONOMIC_POLICY_RESEARCH',
  REAL_ESTATE_FINANCE = 'REAL_ESTATE_FINANCE',
  INSURANCE_UNDERWRITING = 'INSURANCE_UNDERWRITING',

  // ─────────────────────────────────────────────────────────────
  // ENGINEERING (NON-SOFTWARE)
  // ─────────────────────────────────────────────────────────────

  MECHANICAL_ENGINEERING = 'MECHANICAL_ENGINEERING',
  CAD_CAM_DESIGN = 'CAD_CAM_DESIGN',
  THERMAL_FLUID_SYSTEMS_ENGINEERING = 'THERMAL_FLUID_SYSTEMS_ENGINEERING',
  MANUFACTURING_PROCESS_ENGINEERING = 'MANUFACTURING_PROCESS_ENGINEERING',
  PRODUCT_DESIGN_ENGINEERING = 'PRODUCT_DESIGN_ENGINEERING',

  ELECTRICAL_ELECTRONICS_ENGINEERING = 'ELECTRICAL_ELECTRONICS_ENGINEERING',
  POWER_SYSTEMS_ENERGY_ENGINEERING = 'POWER_SYSTEMS_ENERGY_ENGINEERING',
  RF_COMMUNICATIONS_ENGINEERING = 'RF_COMMUNICATIONS_ENGINEERING',
  PCB_HARDWARE_DESIGN = 'PCB_HARDWARE_DESIGN',
  SIGNAL_IMAGE_PROCESSING = 'SIGNAL_IMAGE_PROCESSING',
  FPGA_ASIC_DESIGN = 'FPGA_ASIC_DESIGN',

  CIVIL_STRUCTURAL_ENGINEERING = 'CIVIL_STRUCTURAL_ENGINEERING',
  GEOTECHNICAL_ENGINEERING = 'GEOTECHNICAL_ENGINEERING',
  TRANSPORTATION_INFRASTRUCTURE = 'TRANSPORTATION_INFRASTRUCTURE',
  WATER_RESOURCES_ENGINEERING = 'WATER_RESOURCES_ENGINEERING',
  CONSTRUCTION_MANAGEMENT = 'CONSTRUCTION_MANAGEMENT',

  CHEMICAL_MATERIALS_ENGINEERING = 'CHEMICAL_MATERIALS_ENGINEERING',
  PROCESS_PLANT_ENGINEERING = 'PROCESS_PLANT_ENGINEERING',
  MATERIALS_SCIENCE_METALLURGY = 'MATERIALS_SCIENCE_METALLURGY',
  POLYMER_COMPOSITE_ENGINEERING = 'POLYMER_COMPOSITE_ENGINEERING',

  AEROSPACE_HARDWARE_ENGINEERING = 'AEROSPACE_HARDWARE_ENGINEERING',
  AVIONICS_FLIGHT_SYSTEMS = 'AVIONICS_FLIGHT_SYSTEMS',
  PROPULSION_SYSTEMS = 'PROPULSION_SYSTEMS',
  SYSTEMS_INTEGRATION_TESTING = 'SYSTEMS_INTEGRATION_TESTING',

  NUCLEAR_ENERGY_ENGINEERING = 'NUCLEAR_ENERGY_ENGINEERING',
  RENEWABLE_ENERGY_ENGINEERING = 'RENEWABLE_ENERGY_ENGINEERING',
  INDUSTRIAL_AUTOMATION_SCADA = 'INDUSTRIAL_AUTOMATION_SCADA',

  // ─────────────────────────────────────────────────────────────
  // HEALTHCARE, LIFE SCIENCES, & RESEARCH
  // ─────────────────────────────────────────────────────────────

  MEDICINE_CLINICAL_HEALTHCARE = 'MEDICINE_CLINICAL_HEALTHCARE',
  INTERNAL_MEDICINE_PRIMARY_CARE = 'INTERNAL_MEDICINE_PRIMARY_CARE',
  SURGERY_INTERVENTIONAL_MEDICINE = 'SURGERY_INTERVENTIONAL_MEDICINE',
  NURSING_ALLIED_HEALTH = 'NURSING_ALLIED_HEALTH',
  TELEMEDICINE_DIGITAL_HEALTH = 'TELEMEDICINE_DIGITAL_HEALTH',
  MEDICAL_DEVICE_DEVELOPMENT = 'MEDICAL_DEVICE_DEVELOPMENT',
  HEALTH_INFORMATICS_EMR = 'HEALTH_INFORMATICS_EMR',
  HEALTHCARE_OPERATIONS_MANAGEMENT = 'HEALTHCARE_OPERATIONS_MANAGEMENT',
  PUBLIC_HEALTH_EPIDEMIOLOGY = 'PUBLIC_HEALTH_EPIDEMIOLOGY',

  BIOTECHNOLOGY_LAB_RESEARCH = 'BIOTECHNOLOGY_LAB_RESEARCH',
  MOLECULAR_BIOLOGY_GENOMICS = 'MOLECULAR_BIOLOGY_GENOMICS',
  SYNTHETIC_BIOLOGY = 'SYNTHETIC_BIOLOGY',
  CELL_TISSUE_ENGINEERING = 'CELL_TISSUE_ENGINEERING',
  BIOINFORMATICS_COMPUTATIONAL_BIOLOGY = 'BIOINFORMATICS_COMPUTATIONAL_BIOLOGY',

  PHARMACEUTICALS = 'PHARMACEUTICALS',
  DRUG_DISCOVERY_DEVELOPMENT = 'DRUG_DISCOVERY_DEVELOPMENT',
  CLINICAL_TRIALS_REGULATORY_AFFAIRS = 'CLINICAL_TRIALS_REGULATORY_AFFAIRS',
  PHARMACOLOGY_TOXICOLOGY = 'PHARMACOLOGY_TOXICOLOGY',
  MEDICAL_AFFAIRS = 'MEDICAL_AFFAIRS',

  PSYCHOLOGY_MENTAL_HEALTH = 'PSYCHOLOGY_MENTAL_HEALTH',
  CLINICAL_COUNSELING_PSYCHOLOGY = 'CLINICAL_COUNSELING_PSYCHOLOGY',
  BEHAVIORAL_COGNITIVE_SCIENCE = 'BEHAVIORAL_COGNITIVE_SCIENCE',
  NEUROSCIENCE_RESEARCH = 'NEUROSCIENCE_RESEARCH',
  ORGANIZATIONAL_INDUSTRIAL_PSYCHOLOGY = 'ORGANIZATIONAL_INDUSTRIAL_PSYCHOLOGY',

  ENVIRONMENTAL_SCIENCE_SUSTAINABILITY = 'ENVIRONMENTAL_SCIENCE_SUSTAINABILITY',
  CLIMATE_SCIENCE_POLICY = 'CLIMATE_SCIENCE_POLICY',
  ECOLOGICAL_CONSERVATION_BIOLOGY = 'ECOLOGICAL_CONSERVATION_BIOLOGY',
  ENVIRONMENTAL_IMPACT_ASSESSMENT = 'ENVIRONMENTAL_IMPACT_ASSESSMENT',
  CIRCULAR_ECONOMY_SUSTAINABILITY = 'CIRCULAR_ECONOMY_SUSTAINABILITY',

  NUTRITION_DIETETICS = 'NUTRITION_DIETETICS',
  PHYSICAL_THERAPY_REHABILITATION = 'PHYSICAL_THERAPY_REHABILITATION',
  VETERINARY_ANIMAL_SCIENCE = 'VETERINARY_ANIMAL_SCIENCE',

  // ─────────────────────────────────────────────────────────────
  // EDUCATION, WRITING, & HUMANITIES
  // ─────────────────────────────────────────────────────────────

  TEACHING_INSTRUCTIONAL_DESIGN = 'TEACHING_INSTRUCTIONAL_DESIGN',
  CURRICULUM_DEVELOPMENT = 'CURRICULUM_DEVELOPMENT',
  ELEARNING_PLATFORM_DEVELOPMENT = 'ELEARNING_PLATFORM_DEVELOPMENT',
  HIGHER_EDUCATION_ACADEMIA = 'HIGHER_EDUCATION_ACADEMIA',
  CORPORATE_TRAINING_FACILITATION = 'CORPORATE_TRAINING_FACILITATION',
  STEM_EDUCATION = 'STEM_EDUCATION',
  EDTECH_PRODUCT_DEVELOPMENT = 'EDTECH_PRODUCT_DEVELOPMENT',

  ACADEMIC_RESEARCH_WRITING = 'ACADEMIC_RESEARCH_WRITING',
  SCIENTIFIC_GRANT_WRITING = 'SCIENTIFIC_GRANT_WRITING',
  PUBLISHING_EDITORIAL = 'PUBLISHING_EDITORIAL',
  JOURNALISM_INVESTIGATIVE_REPORTING = 'JOURNALISM_INVESTIGATIVE_REPORTING',
  GHOSTWRITING_NARRATIVE_NONFICTION = 'GHOSTWRITING_NARRATIVE_NONFICTION',
  CREATIVE_FICTION_WRITING = 'CREATIVE_FICTION_WRITING',
  SPEECHWRITING = 'SPEECHWRITING',

  TRANSLATION_LINGUISTICS = 'TRANSLATION_LINGUISTICS',
  LOCALIZATION_INTERNATIONALIZATION = 'LOCALIZATION_INTERNATIONALIZATION',
  COMPUTATIONAL_LINGUISTICS = 'COMPUTATIONAL_LINGUISTICS',
  SIGN_LANGUAGE_ACCESSIBILITY = 'SIGN_LANGUAGE_ACCESSIBILITY',
  LANGUAGE_INSTRUCTION = 'LANGUAGE_INSTRUCTION',

  PHILOSOPHY_ETHICS = 'PHILOSOPHY_ETHICS',
  HISTORY_ARCHIVAL_RESEARCH = 'HISTORY_ARCHIVAL_RESEARCH',
  POLITICAL_SCIENCE_POLICY_ANALYSIS = 'POLITICAL_SCIENCE_POLICY_ANALYSIS',
  SOCIOLOGY_ANTHROPOLOGY = 'SOCIOLOGY_ANTHROPOLOGY',

  // ─────────────────────────────────────────────────────────────
  // INTERPERSONAL & LEADERSHIP (SOFT SKILLS)
  // ─────────────────────────────────────────────────────────────

  EXECUTIVE_LEADERSHIP_MENTORSHIP = 'EXECUTIVE_LEADERSHIP_MENTORSHIP',
  GENERAL_MANAGEMENT = 'GENERAL_MANAGEMENT',
  BOARD_GOVERNANCE_ADVISORY = 'BOARD_GOVERNANCE_ADVISORY',
  CHANGE_MANAGEMENT = 'CHANGE_MANAGEMENT',
  STARTUP_FOUNDING_ENTREPRENEURSHIP = 'STARTUP_FOUNDING_ENTREPRENEURSHIP',

  CROSS_FUNCTIONAL_COLLABORATION = 'CROSS_FUNCTIONAL_COLLABORATION',
  STAKEHOLDER_MANAGEMENT = 'STAKEHOLDER_MANAGEMENT',
  REMOTE_DISTRIBUTED_TEAM_MANAGEMENT = 'REMOTE_DISTRIBUTED_TEAM_MANAGEMENT',
  MATRIX_ORGANIZATION_INFLUENCE = 'MATRIX_ORGANIZATION_INFLUENCE',

  CRITICAL_THINKING_PROBLEM_SOLVING = 'CRITICAL_THINKING_PROBLEM_SOLVING',
  SYSTEMS_THINKING = 'SYSTEMS_THINKING',
  DATA_DRIVEN_DECISION_MAKING = 'DATA_DRIVEN_DECISION_MAKING',
  DESIGN_THINKING_INNOVATION = 'DESIGN_THINKING_INNOVATION',
  FIRST_PRINCIPLES_REASONING = 'FIRST_PRINCIPLES_REASONING',

  NEGOTIATION_CONFLICT_RESOLUTION = 'NEGOTIATION_CONFLICT_RESOLUTION',
  EXECUTIVE_COMMUNICATION_PRESENTATION = 'EXECUTIVE_COMMUNICATION_PRESENTATION',
  ACTIVE_LISTENING_FACILITATION = 'ACTIVE_LISTENING_FACILITATION',
  COACHING_PERFORMANCE_MANAGEMENT = 'COACHING_PERFORMANCE_MANAGEMENT',
  CULTURAL_INTELLIGENCE_GLOBAL_FLUENCY = 'CULTURAL_INTELLIGENCE_GLOBAL_FLUENCY',
  EMOTIONAL_INTELLIGENCE = 'EMOTIONAL_INTELLIGENCE',
  WRITING_ASYNCHRONOUS_COMMUNICATION = 'WRITING_ASYNCHRONOUS_COMMUNICATION',

  // ─────────────────────────────────────────────────────────────
  // CONSULTING & STRATEGY
  // ─────────────────────────────────────────────────────────────

  MANAGEMENT_CONSULTING = 'MANAGEMENT_CONSULTING',
  DIGITAL_TRANSFORMATION_CONSULTING = 'DIGITAL_TRANSFORMATION_CONSULTING',
  IT_ENTERPRISE_ARCHITECTURE = 'IT_ENTERPRISE_ARCHITECTURE',
  BUSINESS_PROCESS_OUTSOURCING = 'BUSINESS_PROCESS_OUTSOURCING',
  DUE_DILIGENCE_ADVISORY = 'DUE_DILIGENCE_ADVISORY',
  STRATEGY_CORPORATE_DEVELOPMENT = 'STRATEGY_CORPORATE_DEVELOPMENT',

  // ─────────────────────────────────────────────────────────────
  // RESEARCH & EMERGING FIELDS
  // ─────────────────────────────────────────────────────────────

  QUANTUM_COMPUTING_RESEARCH = 'QUANTUM_COMPUTING_RESEARCH',
  SPACE_TECHNOLOGY_RESEARCH = 'SPACE_TECHNOLOGY_RESEARCH',
  NANOTECHNOLOGY_MATERIALS_RESEARCH = 'NANOTECHNOLOGY_MATERIALS_RESEARCH',
  LONGEVITY_AGING_RESEARCH = 'LONGEVITY_AGING_RESEARCH',
  SYNTHETIC_MEDIA_DEEPFAKE_RESEARCH = 'SYNTHETIC_MEDIA_DEEPFAKE_RESEARCH',
  ETHICS_AI_POLICY_RESEARCH = 'ETHICS_AI_POLICY_RESEARCH',
}
